# Generated by Django 4.2.7 on 2023-12-07 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="rooms",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
