# Generated by Django 4.2.7 on 2023-12-16 22:36

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(default=chat.models.get_default_expire_date),
        ),
    ]
