# Generated by Django 4.2.7 on 2023-12-16 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created"]},
        ),
    ]
