# Generated by Django 4.2.7 on 2023-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatuser",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="chatuser",
            name="profile_pic",
            field=models.ImageField(default=1, upload_to="profile_pics/"),
            preserve_default=False,
        ),
    ]
