# Generated by Django 4.2.7 on 2023-12-07 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chatuser", "0002_chatuser_birthdate_chatuser_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatuser",
            name="birthdate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
