# Generated by Django 4.2.7 on 2023-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatuser", "0003_alter_chatuser_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatuser",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="chatuser",
            name="profile_pic",
            field=models.ImageField(default="default.png", upload_to="profile_pics/"),
        ),
    ]
